### ISSUE TITLE
Visor apps fail to reconnect Streams

### ISSUE THREAD

**Issue by ivcosla** [SkycoinProject/skywire-mainnet#12]
Under `milestone2` branches, after a visor is restarted, communication between apps on different visors fails.

**Steps to Reproduce**
1) Run generic integration environment
2) Run `make integration-startup`
3) Run `curl --data  {'"recipient":"'$PK_A'", "message":"Hello Joe!"}' -X POST  $CHAT_C`
4) Check that on visor A the message appears and `skychat` has trashed the "Hello Joe!" message
5) Stop and restart `visor-c`
6) Run step 3) again. Now you should see on node A `No stream of given ID` messages, and thus it being unable to deliver it to `skychat` app
Additionally, if in step 5) we restart `visor-b` instead of `visor-c` we will see that visors `a` and `c` continuously try to reconnect with it without success.

Attached are logs collected from the described scenario.
[visor-a.txt](https://github.com/SkycoinProject/skywire-mainnet/files/3686401/visor-a.txt)
[visor-b.txt](https://github.com/SkycoinProject/skywire-mainnet/files/3686402/visor-b.txt)
[visor-c.txt](https://github.com/SkycoinProject/skywire-mainnet/files/3686403/visor-c.txt)

**Comment by nkryuchkov** [comment]
Cannot be reproduced anymore, fixed in https://github.com/SkycoinProject/skywire-mainnet/pull/53
