### ISSUE TITLE
Fix hypervisor endpoints

### ISSUE THREAD

**Issue by jdknives** [SkycoinProject/skywire-mainnet#14]
The following endpoints seem to be broken: 

- `PUT /api/nodes/{pk}/apps/{apps}`

- `POST /api/nodes/{pk}/transports`

- `DELETE /api/nodes/{pk}/transports/{tid}`

**Comment by Senyoret1** [comment]
I used `POST /api/nodes/{pk}/transports` and was able to create a transport from a local node to another local node. However, both `GET /api/nodes/{pk}/transports/{tid}` and `DELETE /api/nodes/{pk}/transports/{tid}` failed when I tried to use them, I always got as response `can not find app of name  from node` followed by the node key.

Also, there si a problem with `GET /api/nodes/{pk}`: it returns the `transports.log` field for the mocked visors, but not for the real ones. The responses should be consistent for both. I think it would make sense to always return the `transports.log` field, or at least a `logs` parameter could be added, as in `GET /api/nodes/{pk}/transports`.

I made the tests with the `master` branch, as I was not able to run anything with the `mainnet-milestone2` branch. Also, I did not check `PUT /api/nodes/{pk}/apps/{apps}`.

**Comment by ivcosla** [comment]
I'm dealing with some usability issues on the routes endpoints, which need information that is currently not being returned by any of the other endpoints.

Also there is a but with delete transports that needs to be fixed. You should have it ready by tomorrow.

**Comment by ivcosla** [comment]
@Senyoret1 hypervisor documentation is now updated and the endpoints are fixed, except for the 
`transports.log` thing, which is another issue on it's own.

Note that we have renamed `/api/nodes/...` to `/api/visors/...`

**Comment by Senyoret1** [comment]
@ivcosla Thank you, I will take a look tomorrow :+1:

**Comment by Senyoret1** [comment]
@ivcosla I tried to use the endpoint, had some problems with the `mainnet-milestone2` branch and filed some issue. Howerever, was this not going to be for milestone 1?

**Comment by ivcosla** [comment]
For now I will close this issue because the endpoints listed here were fixed at api level.
