### ISSUE TITLE
Service Discovery Client

### ISSUE THREAD

**Issue by jdknives** [SkycoinProject/skywire-mainnet#15]
**Feature description**

https://github.com/SkycoinPro/skywire-service-proxy-discovery 

We need a client for this discovery service. This discovery enables Visors to advertise themselves with their geolocation to other visors wanting to connect. 

**Is your feature request related to a problem? Please describe.**
Users should be able to connect to visors with certain properties (geolocation, connection characteristics etc). Most important for now is the location.

**Comment by nkryuchkov** [comment]
We will also need to Integrate the proxy discovery with the proxy and the hypervisor

**Comment by jdknives** [comment]
For reference, I attach two images from the testnet UI. We are looking to build something quite similar to that. The UI needs to look different obviously, but it would be good to get PubKey and Location.
![4](https://user-images.githubusercontent.com/36450093/78773870-26206780-7994-11ea-961d-40dda8c976e3.PNG)
![6](https://user-images.githubusercontent.com/36450093/78773872-27519480-7994-11ea-9a9e-606cfffa7aab.PNG)
