### ISSUE TITLE
Make install does not work on Windows

### ISSUE THREAD

**Issue by Senyoret1** [SkycoinProject/skywire-mainnet#21]
**Describe the bug**
Running `make install` on windows fails.

**Environment information:**

- OS: Windows 10 (Uasing MinGW32)
- Platform: X64

**Steps to Reproduce**

1. Run `make install` on the root of the repo.

**Actual behavior**
The process exits with the following error:

```
build github.com/SkycoinProject/skywire-mainnet/cmd/skywire-visor: cannot load github.com/sirupsen/logrus/hooks/syslog: no Go source files
```

**Expected behavior**
The proces should finish correctly.

**Additional context**
The only go file inside `vendor/github.com/sirupsen/logrus/hooks/syslog` starts with `// +build !windows,!nacl,!plan9`, so it is ignored on Windows.

**Possible implementation**
Apparently, to be fully multiplatform the code on `github.com/sirupsen/logrus/hooks/syslog` must not be used. The main Skycoin repo also uses logrus, but `vendor/github.com/sirupsen/logrus/hooks/syslog` was no vendored by `dep`, so I think the code in the main repo avoided using that part and that is why it works well on Windows.

**Comment by jdknives** [comment]
@Senyoret1 as Ivan replied already on Telegram, Windows support is not pursued at this stage.
