### ISSUE TITLE
Multiple errors running the hypervisor and visor on mainnet-milestone2

### ISSUE THREAD

**Issue by Senyoret1** [SkycoinProject/skywire-mainnet#22]
**Describe the bug**
Using the `mainnet-milestone2` branch, the hypervisor does not run. Also, the visor has problems connecting to the dmsg server.

**Environment information:**

- OS: Linux (Ubuntu 18.04.1)
- Platform: Linux 4.15.0-65-generic x86_64

**Steps to Reproduce**

1. Run `make install` using the `mainnet-milestone2` branch.

2. Run `hypervisor gen-config -o hypervisor-config.json`, to create a default configuration file for the hypervisor.

3. Run `hypervisor`. It will fail with `Failed to parse rpc port from rpc address: parse :7080: missing protocol scheme`.

4. Open the configuration file created in the second step and change the value of `rpc_addr` to `localhost:7080`.

5. Run `hypervisor` again. It will fail with `Failed to parse rpc port from rpc address: strconv.ParseUint: parsing "": invalid syntax`.

6. Open the configuration file created in the second step again and change the value of `rpc_addr` to `http://skycoin.net:7080`.

7. Run `hypervisor` again. The console will start displaying `no dms_servers found: trying again in 1s... error="Get /dmsg-discovery/available_servers: unsupported protocol scheme """`. The problem with the rpc address appears to be solved.

8. Open the configuration file created in the second step again and change the value of `dmsg_discovery` to `https://messaging.discovery.skywire.skycoin.net`.

9. Run `hypervisor` again. The console will start displaying `no dms_servers found: trying again in 1s... error="Get https://messaging.discovery.skywire.skycoin.net/dmsg-discovery/available_servers: dial tcp: lookup messaging.discovery.skywire.skycoin.net: no such host"`.

In a similar way, trying to run a visor with the default config results in `no dms_servers found: trying again in 1s... error="json: cannot unmarshal number into Go value of type disc.HTTPMessage"` being displayed every second in the console.

**Actual behavior**
The errors previously described appear. Also, the hypervisor is not connecting with the visors, as it does in the `master` branch.

**Expected behavior**
The hypervisor and the visor should work like in the `master branch`, with the default config. If it is currently necessary to run a local dmsg server for making the visor and hypervisor work, it would be good to add instructions in the readme, and it could be also useful in other cases.

**Additional context**

**Possible implementation**

**Comment by Darkren** [comment]
@Senyoret1 currently on the `milestone2` branch hypervisor seems to be running with the default config.  I followed the first 3 of the steps you've described, it started without errors. Please check it out. Regarding the visor - it fails to start, I'll notify you on the progress with this

**Comment by Senyoret1** [comment]
@Darkren Sorry for the late response. I filed this issue while using the `mainnet-milestone2` branch, which I think was removed and is different from the current `milestone2` branch. Maybe this issue is not valid anymore, at least not in the same terms as when I wrote it

**Comment by Darkren** [comment]
Currently on hold. Some of stuff is fixed, needs to be revisited later on when `m2` is ready

**Comment by jdknives** [comment]
Seems to be fixed.
