### ISSUE TITLE
[M1] Integrate dmsgexec and remove skyssh/therealssh.

### ISSUE THREAD

**Issue by evanlinjin** [SkycoinProject/skywire-mainnet#26]
**Tasks:**

- [ ] Remove dmsgexec.
- [ ] Make `dmsgexec` use `ssh` for proper session management.
- [ ] Integrate `dmsgexec` directly into visor.

**Comment by jdknives** [comment]
@evanlinjin this is not Milestone 1. Please merge Milestone 1 first.

**Comment by evanlinjin** [comment]
> @evanlinjin this is not Milestone 1. Please merge Milestone 1 first.

This is not milestone 1? Then what is to be done for milestone 1?

**Comment by jdknives** [comment]
@evanlinjin Long term, we should allow SSH auth with `secp256k1`, but for now it is fine if the authentication happens with any other protocol. We are just trying to get the prototype running.
