### ISSUE TITLE
Error trying to start an app that is already running

### ISSUE THREAD

**Issue by Senyoret1** [SkycoinProject/skywire-mainnet#27]
**Describe the bug**
When calling `PUT /api/visors/{pk}/apps/{app}` with `"status": 1` to start the skychat app when it is already running, the console shows `Failed to start app skychat: app skychat is already started`, but the API does not return anything, so the client stays waiting indefinitely for the API to return something. If the same enpoint is called with `"status": 0` while waiting for the response, the visor sometimes stops being accesible using the hypervisor API.

**Environment information:**

- OS: Linux (Ubuntu 18.04.1)
- Platform: Linux 4.15.0-65-generic x86_64

**Steps to Reproduce**

1. Start some nodes using the `make integration-run-generic` command of the `skywire-services` repository

2. Call `http://{localIp}:8080/api/visors/024ec47420176680816e0406250e7156465e4531f5b26057c9f6297bb0303558c7/apps/skychat` using `PUT` with `{ "autostart": true, "status": 1 }` as content. You should not get a response from this call.

3. Still waiting for the response for the request made in step 2, make a similar request again, but changing the content to `{ "autostart": true, "status": 0 }`.

4. Try repeating steps 3 and 4, so that you will continue trying to start an already started app and then stopping it, until you start getting `"error": "connection is shut down"` as response. You may not need to repeat the previous steps for this to happen, you may start getting that response in the first try.

**Actual behavior**
The call made in step 2 never returs a valid response, even being that the console shows `Failed to start app skychat: app skychat is already started`, which would make a client app unable to give feedback to the user.

Also, the whole procedure eventually makes the console show `Injected [CLOSE]: Closing stream... received=<type:CLOSE><id:…` or `Rejected [ACK]: Failed to grow remote window. error="local record of remote window has become invalid:…`, after which it is not possible to access the visor using the hypervisor API, as it starts returning `"error": "connection is shut down"` all the time.

In fact, there are other ways to make the visor inaccessible via the hypervisor API after step 2, but the process is a bit erratic, so I do not have a specific serie of steps to make it happen.

**Expected behavior**
The call made in stept 2 should return an error and the procedure should not make the visor inaccessible

**Additional context**

**Possible implementation**

**Comment by evanlinjin** [comment]
This bug seems to be also related to https://github.com/SkycoinProject/dmsg

**Comment by evanlinjin** [comment]
@Senyoret1 What branches were you working in to reproduce these issues? For both `skywire-mainnet` and `skywire-services`.

**Comment by Senyoret1** [comment]
mainnet-milestone2 on both repos

**Comment by Senyoret1** [comment]
I tested this again using the `master` branch and the problem of the hypervisor API not returning a valid response is present there too. However, the `master` branch does not appear to have the problem of making the visor inaccessible via the hypervisor API after several attempts, maybe due to the fact that the `mainnet-milestone2` branch was using dmsg.

When trying to stop an already stopped app in the `master` branch the response is `{ "error": "unknown app" }`, so that case would not make the front end wait forever, but the error message could be better.
