### ISSUE TITLE
It is very difficult to delete the transports

### ISSUE THREAD

**Issue by Senyoret1** [SkycoinProject/skywire-mainnet#30]
**Describe the bug**
Using the hypervisor API it is very difficult to delete a transport from a visor, because after removing it from one visor, the other visor will create it again shortly after.

**Environment information:**

- OS: Linux (Ubuntu 18.04.1)
- Platform: Linux 4.15.0-65-generic x86_64

**Steps to Reproduce**

1. Create a transport with the `POST /api/visors/{pk}/transports` API endpoint.

2. Delete the transport with the `DELETE /api/visors/{pk}/transports/{tid}` API endpoint.

3. Use the `GET /api/visors/{pk}/transports` API endpoint to check the current transports list.

**Actual behavior**
If you call the `GET /api/visors/{pk}/transports` API endpoint just after deleting the transport, most likely the transport will not be listed, but after some time it will be there again, as the other visor will create it again.

**Expected behavior**
Transports should stay deleted.

**Additional context**

**Possible implementation**
The operation for deleting the transport should be informed to both visors, to avoid having the transport being created again after a short amount of time. Another option is to make the first visor wait for the second one to try to create the transport again and then inform it that the transport should be deleted there too.

As a temporary workarround, when deleting a transport the Manager could try to delete it in both visors if both are connected to the hypervisor, and show a warning to the user if one of the visors is not connected.

**Comment by jdknives** [comment]
Depends on #10
