### ISSUE TITLE
Add missing options to the hypervisor

### ISSUE THREAD

**Issue by Senyoret1** [SkycoinProject/skywire-mainnet#31]
**Feature description**
The manager UI has some options in the testnet that can not be implemented in the mainnet with the current hypervisor API. The options are:

![o1](https://user-images.githubusercontent.com/34079003/66787717-b339a680-eeb2-11e9-8fb8-1fa5d8b71481.png)

Those options are for setting the address of the discovery service, checking updates for the node/visor and restarting the node/visor. Also, the mainnet UI currently has an option for selecting if the visor should act as an exit node, but there is no API endpoint for making it work.

**Is your feature request related to a problem? Please describe.**
There are some options in the manager that are not working and can not be implemented with the curren API.

**Describe the solution you'd like**
API endpoints must be added to make those options work, or the options should be removed from the UI.

**Describe alternatives you've considered**

**Additional context**

**Possible implementation**

**Comment by jdknives** [comment]
@Senyoret1 We probably do not need to support the discovery option, since I believe it is meant to allow the user to switch the discovery used. I cannot see a use for it right now. The reboot endpoint needs to be implemented I believe and the Update endpoint needs to be discussed with Synth.

**Comment by jdknives** [comment]
Related to #64

**Comment by jdknives** [comment]
Am closing this, as the updating endpoint will be implemented by #153
