### ISSUE TITLE
Routes are removed after several hours

### ISSUE THREAD

**Issue by Senyoret1** [SkycoinProject/skywire-mainnet#44]
**Describe the bug**
When using the instructions written in https://github.com/SkycoinProject/skywire-mainnet/tree/mainnet-milestone2/cmd/hypervisor to use the hypervisor API with the `skywire-services` repo, if some routes are created with `curl --data {'"recipient":"'$PK_A'", "message":"Hello Joe!"}' -X POST $CHAT_C`, the routes start to be returned by the hypervisor API, but are erased after several hours (arround 6 hours), or at least the hypervisor API stops returning them.

**Environment information:**

- OS: Linux (Ubuntu 18.04.1)
- Platform: Linux 4.15.0-65-generic x86_64

**Steps to Reproduce**
It is complicate to see the problem and to have specific instructions about how to reproduce it, because the big amount of time it takes to happen. However, I think it takes about 6 hours without using the hypervisor API to make the problem to appear.

**Actual behavior**
The routes are deleted after several hours. In addition to that, running `curl --data {'"recipient":"'$PK_A'", "message":"Hello Joe!"}' -X POST $CHAT_C` does not recreate them.

**Expected behavior**
Routes should stay.

**Additional context**

**Possible implementation**

**Comment by evanlinjin** [comment]
This is currently expected behavior. Routes are represented as rules in the routing table, and if we don't delete routes within a certain time frame of them not being used, the routing table we eventually get clogged up.

However, this behavior can be improved. If you have some suggestions, please leave them here. Hence, I will leave this ticket open for reasons of discussion.

**Comment by Senyoret1** [comment]
Well, my knowledge in the subject is limited, so I’m not really sure if there is something to be improved. My main concern was that after the route was deleted it was not recreated by calling `curl --data {'"recipient":"'$PK_A'", "message":"Hello Joe!"}' -X POST $CHAT_C `.

**Comment by jdknives** [comment]
@evanlinjin the `curl` command not creating a new route is not expected behavior though, is it?
