### ISSUE TITLE
Remove therealssh from codebase

### ISSUE THREAD

**Issue by jdknives** [SkycoinProject/skywire-mainnet#55]
**Describe the bug**
Dmsgpty suppprt was recently added and there does not seem to be a point in keeping therealssh around. It seems difficult enough to maintain to warrant being removed.

**Comment by jdknives** [comment]
Also, we need to move proxy to port 2 if we go ahead with this, as the port allocation becomes counterintuitive otherwise.

**Comment by nkryuchkov** [comment]
We still have `therealssh` in the codebase, probably it was incorrectly merged after removal.
