### ISSUE TITLE
Make visor listen for stcp transports automatically

### ISSUE THREAD

**Issue by jdknives** [SkycoinProject/skywire-mainnet#71]
**Feature description**

Get local IP address and make visor listen for `stcp` transports on that address and port `7777` by default. 

**Is your feature request related to a problem? Please describe.**
Currently, we have to manipulate the configuration file manually to setup `stcp` transports and set the local IP and port to listen on. All of that should be automated.

**Comment by pikomonde** [comment]
Hmm.. So, previously to make the visor run, we should manipulate manually the config file, which one? This one `/skywire-config.json`?

Then the changes should make the app to listen to stcp on what address? Is it address from the PK on `/skywire-config.json`? So I assume the default local IP is `127.0.0.1:7000`.

So, in config, when the `stcp.local_address` is not there, by default the app will set it to `127.0.0.1:7000`?
