### ISSUE TITLE
It is not possible to make operations related to the routes with the API

### ISSUE THREAD

**Issue by Senyoret1** [SkycoinProject/skywire-mainnet#75]
**Describe the bug**
The hypervisor API has various endpoints that allow to work with the routes, like `GET /nodes/{pk}/routes/{rid}`. The problem is that it is not possible to get the value that must be sent as the `{rid}` param, as the hypervisor API does not have an endpoint for getting the ID of the routes.

Calling the `GET /nodes/{pk}/routes` endpoint only returns a `key` property for each route, which worked before when sent as the `{rid}` param, but not anymore, as the API responds `error: "invalid UUID length: 0"`.

**Possible implementation**
2 possible solutions are:
- Add the ID to the `GET /nodes/{pk}/routes` endpoint.
- Make the API endpoints related to the routes work if the `key` property returned by the `GET /nodes/{pk}/routes` endpoint is sent as the `{rid}` param.

**Comment by jdknives** [comment]
Fixed by #126
